replicaCount: 2

image:
  repository: 550744777186.dkr.ecr.us-east-1.amazonaws.com/dotnet-demo
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  - name: APP_MESSAGE
    value: "Working as Designed ✅"
  - name: APP_VERSION
    value: "1.0.2"
  - name: APP_MISSION
    value: "CentralReach: This amazing Company Commits to empowering people with autism and related intellectual and developmental disabilities (IDDs) and supporting those who serve them"
