apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnet-demo.fullname" . }}
  labels:
    app: {{ include "dotnet-demo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dotnet-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dotnet-demo.name" . }}
    spec:
      containers:
      - name: {{ include "dotnet-demo.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        {{- if .Values.env }}
        env:
        {{- range .Values.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
